version: "3"

services:
  mastermode:
    container_name: "mastermode"
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    depends_on:
      - mongodb

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: